### ISSUE TITLE
Crash on fabric 1.17

### ISSUE THREAD

**Issue by Zano1999** [burgerguy/HUDTweaks#11]
It crash on startup on fabric 1.17
Here the log file: https://pastebin.com/9Uz8mQaL

**Comment by burgerguy** [comment]
I think this is due to Optifine modifying some classes unexpectedly. Instead of crashing, I can have them be disabled at runtime if they fail. I would recommend using Sodium and other CaffieneMC mods over Optifine, but I will stop it from crashing with Optifine next release.

**Comment by Zano1999** [comment]
You were right, I removed optifine and now it works
