### ISSUE TITLE
Bossbars and Titles

### ISSUE THREAD

**Issue by Peter-Crawley** [burgerguy/HUDTweaks#2]
Feature Request

**Comment by burgerguy** [comment]
I have these planned for implementation, but I’m working on mod comparability and translation first. When I'm done with that, I'll add those.

**Comment by burgerguy** [comment]
Added bossbars, just have to add title and subtitle

**Comment by Peter-Crawley** [comment]
Would it be possible for you to add a setting that would allow us to control exactly how many individual bars are visible on the boss bar hud?

**Comment by burgerguy** [comment]
I can do that, but the boss bars are already limited by how many can fit on 1/3 of the screen height. I'm currently trying to figure out how to fix the positioning of them.

**Comment by Peter-Crawley** [comment]
Thanks. I am mainly asking for this because I play on a minecraft server that uses bossbars to indicate various shields but we keep hitting the bossbar limit, this change would be very helpfull.

**Comment by burgerguy** [comment]
Should I add a button to disable the limit entirely or should I add a box where you can type in the maximum amount you want on the screen at a time?

**Comment by Peter-Crawley** [comment]
A maximum would be the best, maybe make it so setting it to 0 or -1 removes the limit?

**Comment by burgerguy** [comment]
I figured out a way to unlimit it, and I’m going to add a slider so it takes up a certain percentage of the screen

**Comment by Peter-Crawley** [comment]
Cool, feel free to give me a testing release and I can see if it works.

**Comment by burgerguy** [comment]
Fixed, will be available in the next release. May need to change some more things, because at least one boss bar still shows up. I’ll push a release when I get the chance.
