### ISSUE TITLE
Crash while switching lobbies on hypixel

### ISSUE THREAD

**Issue by PanJohnny** [burgerguy/HUDTweaks#20]
I have been switching lobbies and the game crashed. Now when I join the server it crashes again. Here is crashy link: https://crashy.net/YpYiQwhfavY9WxMMpoBb

**Comment by burgerguy** [comment]
I think this may be due to other mods in your mods folder. Could you try with just HUDTweaks and see if the bug still happens?

**Comment by PanJohnny** [comment]
I'll take a look at it. Suspect it could be the skyblock mod because it hides hud elements. Maybe that causes the crash.

**Comment by PanJohnny** [comment]
I suspect if you take a look at matrix stack on line 56 (push) method or if you have a mixin there. I suspect that is the problem causer.

```log
at

net.minecraft.client.util.math.MatrixStack.push (MatrixStack:56)

at

com.github.burgerguy.hudtweaks.hud.element.HudElementContainer.tryPushMatrix (ElementContainer:54)
```

**Comment by burgerguy** [comment]
Didn't mean to close this, when I post a release could you let me know if it's fixed?

**Comment by PanJohnny** [comment]
Yeah I'll let you know.
