### ISSUE TITLE
How to i edit position

### ISSUE THREAD

**Issue by InfernoNova9999** [burgerguy/HUDTweaks#4]
is there a button that i should press to get the menu like in the image?

**Comment by burgerguy** [comment]
It should show up when you are in the pause menu in game. In the top right, a button should appear that says “HUDTweaks Config”. You click that and it brings you to the menu. You can also go through ModMenu and click the config button when you click on the mod. You have to be in a world for it to work though.

**Comment by InfernoNova9999** [comment]
thanks
