### ISSUE TITLE
Actionbar

### ISSUE THREAD

**Issue by barraIhsan** [burgerguy/HUDTweaks#5]
As the title says

**Comment by burgerguy** [comment]
Not sure what you mean by Actionbar, is that like the swing percentage bar under the crosshair after you use an item?

**Comment by barraIhsan** [comment]
You can try to run this command
`title @s actionbar {"text":"This is only a test"}`

**Comment by burgerguy** [comment]
I didn't even know that was a feature until now, I'll add it when I get the chance.

**Comment by barraIhsan** [comment]
![image](https://user-images.githubusercontent.com/57800056/112559192-07182100-8e03-11eb-948c-212d93b42234.png)
Yes its added at 1.11

**Comment by burgerguy** [comment]
Fixed in commit c435be9f8a26d2f43ebc85e0c9d15639468964c1, will add title and subtitle when I get the chance.
