### ISSUE TITLE
Incompatibility with Seamless-Loading-Screen

### ISSUE THREAD

**Issue by CodeF53** [burgerguy/HUDTweaks#6]
I am not quite what mod this falls on, but here is the issue:

After repositioning StatusEffects to be next to my hotbar, Seamless loading screen now displays my status effects as of logging out in a really odd location:
![image](https://user-images.githubusercontent.com/37855219/113068513-a7f83a80-917b-11eb-845c-61cf2ecf25c8.png)

**Comment by CodeF53** [comment]
you apparently just need to check options.hudHidden before renering stuff to fix this.

**Comment by burgerguy** [comment]
Vanilla minecraft doesn't disable the status effects when the HUD is hidden (atleast from my glance at the code), so it shows up here. I don't really want to change vanilla functionality, but if you really feel that it's a bug I can force it to check before it renders.
