### ISSUE TITLE
Force Display on Hunger bar doesnt work

### ISSUE THREAD

**Issue by barraIhsan** [burgerguy/HUDTweaks#7]
So i set the force display on the hunger bar to on, but when I ride a horse, its still doesn't appear

**Comment by barraIhsan** [comment]
Wait its actually it is

**Comment by burgerguy** [comment]
Is this in 1.16 or 1.17?

**Comment by barraIhsan** [comment]
1.16

**Comment by burgerguy** [comment]
I just tested it out in 1.16.5 and it seems to work fine. I don't think I've modified any code surrounding it, but it's a possibility that I accidentally fixed it at some point. Could you post the log and what other mods you were using?

![2021-05-03_11 37 06](https://user-images.githubusercontent.com/30326913/116898142-047bc900-ac04-11eb-8209-fe1b415502c3.png)

**Comment by barraIhsan** [comment]
![image](https://user-images.githubusercontent.com/57800056/117092487-8f85cc00-ad88-11eb-9efa-b5740f8efb83.png)
Maybe because [AppleSkin](https://www.curseforge.com/minecraft/mc-mods/appleskin)? Cause that is the **only** that modified my hunger bar

**Comment by burgerguy** [comment]
I couldn’t find any conflicts with appleskin at first glance. Could you try running with no mods and start adding them back until the problem shows back up? That would be a lot easier than looking into each of these separately.

**Comment by burgerguy** [comment]
i changed how the force hunger works, so this should be solved.
