### ISSUE TITLE
Instant Crash on startup

### ISSUE THREAD

**Issue by Onemario1234** [burgerguy/HUDTweaks#9]
It keeps crashing on startup for some reason. Alongside the Crash report, here are my installed mods:
RPG-HUD
Bedrockify
Colormatic
CraftPresence
Dynamic Music
Dynamic Sound Filters
Fabric API
VoxelMap
HUDTweaks
Immersive Portals
Modern Beta
ModMenu
Music Duration Reducer
Pehkui
Physics Mod
Presence Footsteps
Requiem
Roughly Enough Items
Sodium
[crash-2021-05-15_13.59.14-client.txt](https://github.com/burgerguy/HUDTweaks/files/6488203/crash-2021-05-15_13.59.14-client.txt)

**Comment by intact** [comment]
Your ModMenu mod is too old.

**Comment by burgerguy** [comment]
Intact is right, update ModMenu and it should fix the issue

**Comment by Onemario1234** [comment]
> Your ModMenu mod is too old (try Mod Menu v1.16.7 for 1.16.4/5).

> Intact is right, update ModMenu and it should fix the issue

I tried updating and got this on startup.
![image](https://user-images.githubusercontent.com/25996506/118378623-f033b680-b589-11eb-841e-84a0852b6f02.png)

**Comment by Onemario1234** [comment]
The issue was fixed, yes, but now a new issue has arisen.

**Comment by intact** [comment]
If you need new HUD Tweaks (and new ModMenu) you need a newer version of fabric loader. You can install new fabric loader in fabric installer.

**Comment by Onemario1234** [comment]
Ohh, ok. Gotcha. Thanks.
